name: Update Calendar

on:
  schedule:
    # Runs every 5 minutes
    - cron: '*/6 * * * *'
  workflow_dispatch:

jobs:
  update-calendar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main  # Replace 'main' with your default branch

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Configure Git
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"

      - name: Pull latest changes
        run: git pull --rebase

      - name: Run script
        run: python update_calendar.py

      - name: Commit changes
        run: |
          git add corrected_calendar.ics
          timestamp=$(date -u)
          git commit -m "Update calendar ($timestamp)" || echo "No changes to commit"

      - name: Push changes
        run: |
          git push origin HEAD:${{ github.ref }} --force-with-lease
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
